[package]
name = "pin-project-internal"
version = "0.4.9"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/pin-project"
homepage = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project-internal"
keywords = ["pin", "macros", "attribute"]
categories = ["no-std", "rust-patterns"]
description = """
An internal crate to support pin_project - do not use directly
"""

[lib]
proc-macro = true

[dependencies]
pin-project-internal-impl = { version = "=0.4.1", path = "../pin-project-internal-impl", default-features = false }

[dev-dependencies]
pin-project = { version = "0.4.9", path = ".." }
rustversion = "1.0"
