name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '00 01 * * *'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          # This is the minimum supported Rust version of this crate.
          # When updating this, the reminder to update the minimum supported
          # Rust version in README.md.
          - 1.33.0
          - 1.36.0
          - 1.37.0
          - stable
          - beta
          - nightly
          # pin-project itself has no platform-dependent implementation.
          # macOS is only used to check that pin-project can interoperate
          # correctly with `#[cfg()]`.
          - macos
          # - windows
        include:
          - build: 1.33.0
            os: ubuntu-latest
            rust: 1.33.0
          - build: 1.36.0
            os: ubuntu-latest
            rust: 1.36.0
          - build: 1.37.0
            os: ubuntu-latest
            rust: 1.37.0
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: nightly
          # - build: windows
          #   os: windows-latest
          #   rust: nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh ${{ matrix.rust }}
      - name: Install cargo-hack
        if: matrix.rust == 'nightly'
        run: |
          cargo install cargo-hack
      - name: cargo test
        run: |
          cargo test --all --all-features
      - name: cargo test -- --ignored
        if: matrix.rust == 'nightly'
        run: |
          cargo test --all --all-features -- --ignored
      # Refs: https://github.com/rust-lang/cargo/issues/5657
      - name: cargo check -Zminimal-versions
        if: matrix.rust == 'nightly'
        run: |
          cargo update -Zminimal-versions
          cargo hack check --all --all-features --no-dev-deps --ignore-private

  style:
    name: style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - clippy
          - rustfmt
          - rustdoc
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh
      - name: Install component
        if: matrix.component != 'rustdoc'
        shell: bash
        run: |
          . ./ci/install-component.sh ${{ matrix.component }}
      - name: cargo clippy
        if: matrix.component == 'clippy'
        run: |
          cargo clippy --all --all-features
      - name: cargo fmt -- --check
        if: matrix.component == 'rustfmt'
        run: |
          cargo fmt --all -- --check
      - name: cargo doc
        if: matrix.component == 'rustdoc'
        env:
          # TODO: once https://github.com/rust-lang/rust/issues/70814 fixed, remove '-Aunused_braces'
          RUSTDOCFLAGS: -Dwarnings -Aunused_braces
        run: |
          cargo doc --no-deps --all --all-features
